import { useEffect, useRef } from "react";
import { ArrowUpRight, Github } from "lucide-react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useReveal } from "@/hooks/use-reveal";
import { RevealText } from "./RevealText";

gsap.registerPlugin(ScrollTrigger);

const projects = [
  {
    id: 1,
    title: "AI Job Assistant",
    description:
      "AI-powered career tool that analyzes CV-to-job fit in seconds. Returns a match score, strengths & weaknesses breakdown, and a tailored cover letter — generated by DeepSeek in the language of your choice.",
    image: "/projects/AIJobAssistant.png",
    tags: ["Nuxt 3", "TypeScript", "DeepSeek AI", "SCSS"],
    demoUrl: "https://ai-job-application-assistant-eta.vercel.app/",
    githubUrl: "https://github.com/LuisIglesiass/ai-job-application-assistant",
  },
  {
    id: 2,
    title: "Smart Budget Planner",
    description:
      "A personal finance web app focused on budget planning, expense tracking, and clearer money management through a clean, intuitive interface.",
    image: "/projects/SmartBudgetPlanner.png",
    tags: ["React", "Vite", "JavaScript", "Tailwind CSS"],
    demoUrl: "https://smart-budget-planner-jet.vercel.app/",
    githubUrl: "https://github.com/LuisIglesiass/smart-budget-planner",
  },
  {
    id: 3,
    title: "Aesthetic Art Gallery",
    description:
      "A minimalist digital art gallery built with Nuxt and GSAP, focused on refined typography, smooth scroll animations, and a calm, gallery-like visual experience.",
    image: "/projects/AestheticArtGallery.jpg",
    tags: ["Nuxt", "Vue", "GSAP", "ScrollTrigger", "UI/UX"],
    demoUrl: "https://aesthetic-art-gallery.vercel.app/",
    githubUrl: "https://github.com/LuisIglesiass/aesthetic-art-gallery",
  },
  {
    id: 4,
    title: "Smart Energy",
    description:
      "Real-time CO₂ and energy tracking with data visualization and category-based analysis.",
    image: "/projects/SmartEnergy.jpg",
    tags: ["Next.js", "Tailwind CSS", "MongoDB"],
    demoUrl: "https://smart-energy-2e28tkmmo-luis-iglesias-projects.vercel.app",
    githubUrl: "https://github.com/LuisIglesiass/SmartEnergy",
  },
  {
    id: 5,
    title: "Tailwind UI Kit",
    description:
      "A modern, responsive UI components library built with Tailwind CSS and React, featuring clean design, ready-to-use components, and easy customization.",
    image: "/projects/MyUiKit.jpg",
    tags: ["React", "Tailwind CSS", "Vite"],
    demoUrl: "https://my-ui-kit-ten.vercel.app/",
    githubUrl: "https://github.com/LuisIglesiass/tailwind-ui-kit",
  },
  {
    id: 6,
    title: "HabitFlow",
    description:
      "Minimalist habit tracker with progress visualization and smart tracking features.",
    image: "/projects/HabitFlow.jpg",
    tags: ["React", "Tailwind", "TypeScript"],
    githubUrl: "https://github.com/LuisIglesiass/habit-tracker",
  },
  {
    id: 7,
    title: "Movie Searcher",
    description:
      "Fast and minimal movie search tool using OMDb API and pure JavaScript.",
    image: "/projects/MovieSearcher.jpg",
    tags: ["JavaScript", "CSS", "HTML"],
    demoUrl: "https://findmyfilm-neon.vercel.app/",
    githubUrl: "https://github.com/LuisIglesiass/movie-search-js",
  },
  {
    id: 8,
    title: "FocusList",
    description:
      "Clean to-do app for managing tasks with real-time stats and local storage.",
    image: "/projects/FocusList.jpg",
    tags: ["JavaScript", "React", "Vite", "localStorage"],
    demoUrl: "https://focuslist-drab.vercel.app/",
    githubUrl: "https://github.com/LuisIglesiass/todo-app-react",
  },
  {
    id: 9,
    title: "Simple Calculator",
    description: "Lightweight calculator designed for quick and easy calculations.",
    image: "/projects/CalculatorApp.jpg",
    tags: ["JavaScript", "CSS", "HTML"],
    demoUrl: "https://calculator-app-snowy-mu.vercel.app/",
    githubUrl: "https://github.com/LuisIglesiass/calculator-app",
  },
];

const ProjectCard = ({ project, index }) => {
  const ref = useReveal();
  const imgRef = useRef(null);

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const img = imgRef.current;
    if (!img) return;

    const ctx = gsap.context(() => {
      gsap.fromTo(
        img,
        { yPercent: -16 },
        {
          yPercent: -4,
          ease: "none",
          scrollTrigger: {
            trigger: img,
            start: "top bottom",
            end: "bottom top",
            scrub: true,
          },
        }
      );
    });
    return () => ctx.revert();
  }, []);

  return (
    <article
      ref={ref}
      className="rail-item w-[82vw] sm:w-[420px] rounded-2xl border border-border bg-card overflow-hidden group card-hover"
    >
      <div className="h-56 overflow-hidden relative">
        <div ref={imgRef} className="w-full h-[130%]">
          <img
            src={project.image}
            alt={project.title}
            loading="lazy"
            className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
          />
        </div>
        <span className="absolute top-3 left-3 font-mono text-xs bg-background px-2.5 py-1 rounded-full text-muted-foreground border border-border">
          0{index + 1}
        </span>
      </div>

      <div className="p-6">
        <div className="flex flex-wrap gap-2 mb-4">
          {project.tags.map((tag) => (
            <span
              key={tag}
              className="px-2.5 py-1 text-[11px] font-mono rounded-full bg-secondary text-secondary-foreground"
            >
              {tag}
            </span>
          ))}
        </div>

        <h3 className="font-display text-xl mb-2">{project.title}</h3>
        <p className="text-muted-foreground text-sm leading-relaxed mb-5 font-mono">
          {project.description}
        </p>

        <div className="flex gap-4 font-mono text-xs">
          {project.demoUrl && (
            <a
              href={project.demoUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1 text-foreground/80 hover:text-primary transition-colors"
            >
              Live <ArrowUpRight size={14} />
            </a>
          )}
          <a
            href={project.githubUrl}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1 text-foreground/80 hover:text-primary transition-colors"
          >
            <Github size={14} /> Code
          </a>
        </div>
      </div>
    </article>
  );
};

export const ProjectsSection = () => {
  return (
    <section id="projects" className="py-28 relative">
      <div className="container px-6 md:px-12">
        <p className="index-number mb-3">CATALOGUE</p>
        <RevealText as="h2" text="Selected work" className="font-display text-3xl md:text-4xl mb-4 block" />
        <p className="font-mono text-sm text-muted-foreground mb-10 max-w-xl">
          Nine shipped projects. Scroll sideways to browse.
        </p>
      </div>

      <div className="rail px-6 md:px-12">
        {projects.map((project, i) => (
          <ProjectCard key={project.id} project={project} index={i} />
        ))}
      </div>

      <div className="container px-6 md:px-12 mt-10">
        <a
          className="btn-outline w-fit inline-flex group"
          target="_blank"
          rel="noreferrer"
          href="https://github.com/LuisIglesiass"
        >
          See everything on GitHub
          <ArrowUpRight size={15} className="transition-transform duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
        </a>
      </div>
    </section>
  );
};
